[k3s_master]
k3smaster ansible_host=192.168.100.35 ansible_user=k3smaster

[k3s_workers]
k3sworker1 ansible_host=192.168.100.36 ansible_user=k3sworker1
k3sworker2 ansible_host=192.168.100.37 ansible_user=k3sworker2

[all:vars]
ansible_ssh_private_key_file=/home/master/.ssh/id_ed25519
ansible_become=yes
ansible_become_method=sudo
